### ISSUE TITLE
Website video disappeared

### ISSUE THREAD

**Issue by Jamesinvi** [CodingTrain/Rainbow-Code#424]
the 69.4 video on genetic algorithms and steering behaviours is no longer available on the website

**Comment by nilsweb** [comment]
Thanks for noticing! This is due to the changes introduced in 19701e5f0e3226008e2e7763654e49704fe8e3ee.

Instead of
``` yaml
contributions:
- title: "JamesInvi's Multiple Organism Simulator (with graph)"
  author:JamesInvi
    name: "James (Invi) Karran"
    url: "https://github.com/Jamesinvi/Animosity"
  url: "https://github.com/Jamesinvi/Animosity"
  source: "https://github.com/Jamesinvi/Animosity"
```
it should be
``` yaml
contributions:
  - title: "JamesInvi's Multiple Organism Simulator (with graph)"
    author:
      name: "James (Invi) Karran"
      url: "https://github.com/Jamesinvi/Animosity"
    url: "https://github.com/Jamesinvi/Animosity"
    source: "https://github.com/Jamesinvi/Animosity"
```
If you like, you can go ahead an fix it.
